Add throttle to tracking data
velocity-inc/velocity-sdk-ios pull request #9
Opened 2017-10-13 13:33 UTC by Antanas

2017-10-16 12:01 UTC, dynbit requested changes
Few changes still needed. 

Another question, is there a way, to know that our SDK reached day limit? Seems like there is no way to know/track that.

2017-10-16 12:01 UTC, dynbit commented on VelocitySDK/Core/VLTDataThrottler.m
> +        self.sentDataDict = [NSMutableDictionary dictionaryWithDictionary:storedDict];
`[storedDict mutableCopy]`?

2017-10-16 12:01 UTC, dynbit commented on VelocitySDK/Core/VLTDataThrottler.m
> +        NSUInteger sent = [self.sentDataDict[[self todaysKey]] unsignedIntegerValue];
Make `[self todaysKey]` a readonly property ?

2017-10-16 12:01 UTC, dynbit commented on VelocitySDK/Core/VLTDataThrottler.m
> +    NSDate * date = [NSDate date];
Space after `*`

2017-10-16 12:01 UTC, dynbit commented on Tests/VLTDataThrottlerTests.m
> +    OCMStub([self.reachability isReachableViaWWAN]).andReturn(true);
Can you change this test to reach throttler limit in multiple steps instead of one step?

2017-10-16 12:01 UTC, dynbit commented on VelocitySDK/Core/VLTDataThrottler.m
> +    [[NSUserDefaults standardUserDefaults] setValue:self.sentDataDict forKey:VLTDataThrottlerKey];
I would add `[[NSUserDefaults standardUserDefaults] synchronize];` just to be sure. Or maybe it isn't needed as you are keeping that dictionary in memory. What do you think?

2017-10-16 12:01 UTC, dynbit commented on Tests/Operations/VLTCaptureUploadOperationTests.m
> -    op.onError = ^(NSError *error) {
As you have added `@property (atomic, copy) void(^onSuccess)(NSUInteger bytesSent);` it would be nice to have it covered in tests as well.

2017-10-17 10:30 UTC, Antanas commented on VelocitySDK/Core/VLTDataThrottler.m
> +        self.sentDataDict = [NSMutableDictionary dictionaryWithDictionary:storedDict];
Well ```storedDict``` will be nil for the first time so we would need ```if else ``` statement to handle this. Leaving this oneliner :)

2017-10-17 10:55 UTC, dynbit approved these changes
👍

2017-10-17 10:57 UTC, merged